#!/bin/bash
# nm sets this values

MYCON_UUID=50194c8b-16e2-44f3-a0a1-aa2655293c33
MYCON_UUID2=45f963a7-5082-4157-8396-741b7cb3a40e

if [ "$CONNECTION_UUID" == "$MYCON_UUID" ] then
	sudo mount -t cifs -o username=derpa,password=ananas35KAS,uid=1000,gid=1000 //192.168.1.88/mediashare/Sites /home/derpa/sites
elif [ "$CONNECTION_UUID" == "$MYCON_UUID2" ] then
	sudo mount -t cifs -o username=derpa,password=ananas35KAS,uid=1000,gid=1000 //192.168.1.88/mediashare/Sites /home/derpa/sites
else

fi
