#!/bin/bash
SSID="Tjov5G"
SSID2="Tjov"
ESSID=`iw wlx501ac50e9426 link | grep SSID | cut -d" " -f2`

if [[ $1 == "wlx501ac50e9426" && $2 == up && ( $ESSID == $SSID || $ESSID == $SSID2 ) ]]; then
sudo umount /home/derpa/sites/
sudo mount -t cifs -o guest //192.168.1.88/mediashare/Sites/ /home/derpa/sites
fi
